### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by joethephish** [isakgrozny/palimpsest-nw#1]
1. I needed to install `gulp`, which isn't in the instructions.
2. I got this error:

![image](https://cloud.githubusercontent.com/assets/858967/16712643/878a7fa6-4685-11e6-9679-c9dcd5ab7d71.png)

**Comment by ladyisidore** [comment]
1. D'oh. I knew I forgot something obvious. Updated the README with instructions to install the Gulp CLI.
2. I'm not 100% positive on this, but the error might be due to using Gulp 3.9, while I've switched to the unreleased but decently stable Gulp 4 development version. Can you try updating/installing `gulp-cli` (globally), deleting `node_modules` in the repository folder and attempting the build again?

If that's not it, I'll investigate it later this afternoon. Right now I'm on a train somewhere in the middle of Germany and it keeps going into tunnels that interrupt my connection.

**Comment by joethephish** [comment]
Yup, that worked, thanks. Cool demo!
